functionsDirectory = ".\YogaFrontend\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = ".\YogaFrontend\\dist"
publishOrigin = "ui"
base = ".\YogaFrontend"
command = "npm run build"
commandOrigin = "ui"
functions = ".\YogaFrontend\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]